In [1]:
import tensorflow as tf
import gensim
tf.__version__
import nltk  # 영어 자연어처리 패키지
nltk.__version__

'3.4.5'

In [9]:
?gensim.topic_coherence.text_analysis.Word2Vec('hi')

Object `gensim.topic_coherence.text_analysis.Word2Vec('hi')` not found.


In [10]:
nltk.download()  # nltk data 다운로드
# nltk.download('treebank')  # treebank 설치

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [3]:
import konlpy
konlpy.__version__

'0.5.2'

In [4]:
# 토큰화, 정제, 정규화
# 토큰(단어)화 : 어절, 단어, 문장, 문단

# 단어 토큰화 : 구두점, 특수문자 제거

from nltk.tokenize import word_tokenize
from nltk.tokenize import WordPunctTokenizer
from tensorflow.keras.preprocessing.text import text_to_word_sequence

from nltk.tokenize import TreebankWordTokenizer

In [5]:
# 가장 많이 쓰임
print('nltk.tokenize \ word_tokenize : ',word_tokenize("Mr. Jone's Don't be!?  $100  3.14"))

# 클래스 객체 생성
wpt=WordPunctTokenizer()
print('nltk.tokenize / WordPunctTokenizer : ',wpt.tokenize("Mr. Jone's Don't be!?  $100  3.14"))

# keras token화
print('tensorflow.keras.preprocessing.text / text_to_word_sequence : ',text_to_word_sequence("Mr. Jone's Don't be!?  $100  3.14"))

# 표준.
twt=TreebankWordTokenizer()
print('nltk.tokenize / TreebankWordTokenizer : ',twt.tokenize("Mr. Jone's Don't be!?  $100  3.14"))


nltk.tokenize \ word_tokenize :  ['Mr.', 'Jone', "'s", 'Do', "n't", 'be', '!', '?', '$', '100', '3.14']
nltk.tokenize / WordPunctTokenizer :  ['Mr', '.', 'Jone', "'", 's', 'Don', "'", 't', 'be', '!?', '$', '100', '3', '.', '14']
tensorflow.keras.preprocessing.text / text_to_word_sequence :  ['mr', "jone's", "don't", 'be', '100', '3', '14']
nltk.tokenize / TreebankWordTokenizer :  ['Mr.', 'Jone', "'s", 'Do', "n't", 'be', '!', '?', '$', '100', '3.14']


In [5]:
# 문장단위 토큰화
from nltk.tokenize import sent_tokenize

In [7]:
text = "Python is an interpreted, high-level, general-purpose programming language. Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace. Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects."

print(sent_tokenize(text))

['Python is an interpreted, high-level, general-purpose programming language.', "Created by Guido van Rossum and first released in 1991, Python's design philosophy emphasizes code readability with its notable use of significant whitespace.", 'Its language constructs and object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.']


In [8]:
# 한국어 토큰화
# 조사 : 그녀가(에게, 를, 와, 는 ...)
# 아버지가방에들어가.. 

# 토큰화 작업 : 형태소 (가장 작은 말의 단위) 고려
# -> 자립형태소 / 의존형태소

# 길동이가 파이썬을 합니다
# 자립형태소(길동이, 파이썬) / 의존형태소 (조사, 어미,..)

# 품사 태깅(tagging), fly
# : 토큰화 과정에서 단어가 어떤 품사로 쓰여지는지 

In [6]:
text = 'Python is an interpreted, high-level, general-purpose programming language.'

print(word_tokenize(text))

# 태깅
from nltk.tag import pos_tag
pos_tag(word_tokenize(text))

['Python', 'is', 'an', 'interpreted', ',', 'high-level', ',', 'general-purpose', 'programming', 'language', '.']


[('Python', 'NNP'),
 ('is', 'VBZ'),
 ('an', 'DT'),
 ('interpreted', 'JJ'),
 (',', ','),
 ('high-level', 'JJ'),
 (',', ','),
 ('general-purpose', 'JJ'),
 ('programming', 'NN'),
 ('language', 'NN'),
 ('.', '.')]

In [7]:
# 형태소 분석기
# : Okt, Mecab, Kkma
# : 단어 토큰화가 아님 / 형태소 토큰화를 하는 것임

from konlpy.tag import Okt

In [12]:
okt = Okt()
print(okt.morphs("오늘은 수요일, 내일은 목요일입니다."))

# 태깅까지
print(okt.pos("오늘은 수요일, 내일은 목요일입니다."))

# 명사만
print(okt.nouns("오늘은 수요일, 내일은 목요일입니다."))

# konlpy.org 사이트 참고

['오늘', '은', '수요일', ',', '내일', '은', '목요일', '입니다', '.']
[('오늘', 'Noun'), ('은', 'Josa'), ('수요일', 'Noun'), (',', 'Punctuation'), ('내일', 'Noun'), ('은', 'Josa'), ('목요일', 'Noun'), ('입니다', 'Adjective'), ('.', 'Punctuation')]
['오늘', '수요일', '내일', '목요일']


In [ ]:
# 데이터 정제(전처리) : 불필요한 형태소 제거, 단어 통일 

In [ ]:
# LSA (Latent Semantic Analysis) 잠재의미분석
# : '토픽'으로 유사도를 구하는 알고리즘

# SVD (Singular Value Decomposition) 특이값 분해

In [1]:
import numpy as np
import pandas as pd

In [17]:
# 임의의 DTM 생성
A = np.array([[0,0,0,1,0,1,1,0,0],
              [0,0,0,1,1,0,1,0,0],
              [0,1,1,0,2,0,0,0,0],
              [1,0,0,0,0,0,0,1,1]])
A.shape  # 4, 9

(4, 9)

In [33]:
U, s, VT = np.linalg.svd(A, full_matrices=True)  # full SVD, truncated SVD
U, s, VT
U.round(2), s.round(2), VT.round(2)

(array([[-0.24,  0.75,  0.  , -0.62],
        [-0.51,  0.44, -0.  ,  0.74],
        [-0.83, -0.49, -0.  , -0.27],
        [-0.  , -0.  ,  1.  ,  0.  ]]),
 array([2.69, 2.05, 1.73, 0.77]),
 array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
        [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ],
        [ 0.58, -0.  ,  0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.58,  0.58],
        [ 0.  , -0.35, -0.35,  0.16,  0.25, -0.8 ,  0.16, -0.  , -0.  ],
        [-0.  , -0.78, -0.01, -0.2 ,  0.4 ,  0.4 , -0.2 ,  0.  ,  0.  ],
        [-0.29,  0.31, -0.78, -0.24,  0.23,  0.23,  0.01,  0.14,  0.14],
        [-0.29, -0.1 ,  0.26, -0.59, -0.08, -0.08,  0.66,  0.14,  0.14],
        [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19,  0.75, -0.25],
        [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19, -0.25,  0.75]]))

In [31]:
U.shape   # 4, 4
s.shape   # 4,
VT.shape  # 9, 9

(9, 9)

In [39]:
S = np.zeros([4,9])
S[:4,:4] = np.diag(s)
S.round(2)  # 특이값 행렬

array([[2.69, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 2.05, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.73, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.77, 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [40]:
print(VT.round(2))

[[-0.   -0.31 -0.31 -0.28 -0.8  -0.09 -0.28 -0.   -0.  ]
 [ 0.   -0.24 -0.24  0.58 -0.26  0.37  0.58 -0.   -0.  ]
 [ 0.58 -0.    0.    0.   -0.    0.   -0.    0.58  0.58]
 [ 0.   -0.35 -0.35  0.16  0.25 -0.8   0.16 -0.   -0.  ]
 [-0.   -0.78 -0.01 -0.2   0.4   0.4  -0.2   0.    0.  ]
 [-0.29  0.31 -0.78 -0.24  0.23  0.23  0.01  0.14  0.14]
 [-0.29 -0.1   0.26 -0.59 -0.08 -0.08  0.66  0.14  0.14]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19  0.75 -0.25]
 [-0.5  -0.06  0.15  0.24 -0.05 -0.05 -0.19 -0.25  0.75]]


In [46]:
np.dot(np.dot(U,S),VT).round(1)

array([[ 0.,  0.,  0.,  1., -0.,  1.,  1.,  0.,  0.],
       [ 0., -0., -0.,  1.,  1., -0.,  1., -0., -0.],
       [ 0.,  1.,  1., -0.,  2., -0., -0.,  0.,  0.],
       [ 1., -0.,  0.,  0., -0.,  0., -0.,  1.,  1.]])

In [47]:
A

array([[0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 0, 2, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 1, 1]])

In [49]:
# 두 행렬이 같은지 판단하는 함수
np.allclose(A, np.dot(np.dot(U,S),VT).round(1))

True

In [55]:
VT.round(2)

array([[-0.  , -0.31, -0.31, -0.28, -0.8 , -0.09, -0.28, -0.  , -0.  ],
       [ 0.  , -0.24, -0.24,  0.58, -0.26,  0.37,  0.58, -0.  , -0.  ],
       [ 0.58, -0.  ,  0.  ,  0.  , -0.  ,  0.  , -0.  ,  0.58,  0.58],
       [ 0.  , -0.35, -0.35,  0.16,  0.25, -0.8 ,  0.16, -0.  , -0.  ],
       [-0.  , -0.78, -0.01, -0.2 ,  0.4 ,  0.4 , -0.2 ,  0.  ,  0.  ],
       [-0.29,  0.31, -0.78, -0.24,  0.23,  0.23,  0.01,  0.14,  0.14],
       [-0.29, -0.1 ,  0.26, -0.59, -0.08, -0.08,  0.66,  0.14,  0.14],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19,  0.75, -0.25],
       [-0.5 , -0.06,  0.15,  0.24, -0.05, -0.05, -0.19, -0.25,  0.75]])

In [75]:
# 절단된 SVD
# 토픽을 2개로 하고싶다
S = S[:2,:2]  # 2, 2  토픽 2개
U = U[:,:2]   # 4, 2  문서 4개, 토픽 2개
# U의 의미는 4개 문서 각각에 대한 잠재된 의미를 표현하고 있는 수치문서 백터

VT = VT[:2,:] # 2, 4  단어 4개, 토픽 2개
# VT의 각 열은 잠재 의미를 나타내기 위한 수치화 된 단어 백터

Aprime = np.dot(np.dot(U,S),VT).round(2)
print(Aprime)
print(A)

[[ 0.   -0.17 -0.17  1.08  0.12  0.62  1.08 -0.   -0.  ]
 [ 0.    0.2   0.2   0.91  0.86  0.45  0.91  0.    0.  ]
 [ 0.    0.93  0.93  0.03  2.05 -0.17  0.03  0.    0.  ]
 [ 0.    0.    0.    0.    0.   -0.    0.    0.    0.  ]]
[[0 0 0 1 0 1 1 0 0]
 [0 0 0 1 1 0 1 0 0]
 [0 1 1 0 2 0 0 0 0]
 [1 0 0 0 0 0 0 1 1]]


In [77]:
np.dot(S,VT).round(2)
# (2,9)행의 scatter을 그리고 각 좌표끼리의 cos유사도를 구함

array([[-0.  , -0.83, -0.83, -0.75, -2.16, -0.24, -0.75, -0.  , -0.  ],
       [ 0.  , -0.49, -0.49,  1.2 , -0.53,  0.75,  1.2 , -0.  , -0.  ]])

In [ ]:
'''
        돈     사랑    저는    좋아요
줄거리1  0       1      1       1
줄거리2  1       0      1       1
줄거리3  2       0      2       2
'''
# cos 유사도 공식
# 문서 내접 / 각 문서벡터의 크기

In [83]:
from numpy.linalg import norm

In [86]:
mov1 = np.array([0,1,1,1])
mov2 = np.array([1,0,1,1])
mov3 = np.array([2,0,2,2])

In [93]:
np.dot(mov1,mov2) / (norm(mov1)*norm(mov2))

0.6666666666666667

In [94]:
np.dot(mov2,mov3) / (norm(mov2)*norm(mov3))

1.0000000000000002

In [95]:
def cos_sim(X,Y):
    return np.dot(X,Y) / (norm(X)*norm(Y))

In [96]:
print(cos_sim(mov1, mov2))
print(cos_sim(mov1, mov3))
print(cos_sim(mov2, mov3))

0.6666666666666667
0.6666666666666667
1.0000000000000002


In [2]:
data = pd.read_csv('data/the-movies-dataset/movies_metadata.csv')

data = data[:25000]
data['overview'].isnull().sum()  # 135

# 결측치 채우기
data['overview'] = data['overview'].fillna('')

data['overview'].isnull().sum()

C:\Users\student\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


0

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

# 영어 tf-idf객체 생성
tfidf = TfidfVectorizer(stop_words='english').fit(data['overview'])

# tf-idf 메트릭스 생성
## 원래는 be동사 처리나 동사 형태 처리도 필요함 // 약식으로 test

t=tfidf.transform(data['overview']) # 20000, 47487

t_array = t.toarray()
t_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [4]:
t_array

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [44]:
data['title'][0]
# Toy Story와 가장 코사인 유사도가 큰 영화 10편을 추출 -> 영화 제목과 유사도 출력

'Toy Story'

In [ ]:
np.linalg.svd(t_array, full_matrices=True)


In [33]:
from numpy.linalg import norm

In [34]:
data = pd.read_csv('data/the-movies-dataset/movies_metadata.csv')
data = data[:20000]
data['overview'].fillna('', inplace = True)

tfidf = TfidfVectorizer(stop_words = 'english')
tfidf_mat = tfidf.fit_transform(data['overview'])

# 데이터프레임 생성
tfidf_df = pd.DataFrame(tfidf_mat.toarray())

# 코사인 유사도 구하는 함수
def sim_cos(X, Y):
    return np.dot(X, Y) / ((norm(X) * norm(Y)) + 1e-7)

# 영화 인덱스와 유사도를 묶어서 리스트로 만드는 함수
def top_match(data, movie, simf = sim_cos):
    simList = []
    for i in data.index:
        if movie != i:
            simList.append((simf(data.loc[movie, :], data.loc[i, :]), i))
    return simList

# 유사도가 높은 영화 10개를 영화 제목과 함께 출력
movieList = []
for sim, m_id in sorted(top_match(tfidf_df, 0), reverse = True):
    movieList.append((sim, data.loc[m_id, 'title']))
movieList[:10]

C:\Users\student\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


[(0.5258228774915119, 'Toy Story 3'),
 (0.4626387756002305, 'Toy Story 2'),
 (0.27955408709340457, 'The 40 Year Old Virgin'),
 (0.2006858706012685, 'The Champ'),
 (0.18272966895459847, 'Rebel Without a Cause'),
 (0.15689197655065487, 'For Your Consideration'),
 (0.15273435380284647, 'Condorman'),
 (0.1431988524037047, 'Man on the Moon'),
 (0.13751066537587156, 'Malice'),
 (0.13360660274208175, 'Factory Girl')]